en/common/cloud-code.mdown

We see at least one question related to this common mistake every day in our community forums.

Document common issue people might run into when writing Cloud Code

---

en/common/errors.mdown
en/dotnet/handling-errors.mdown
en/embedded_c/handling-errors.mdown
en/ios/handling-errors.mdown
en/js/handling-errors.mdown
en/php/handling-errors.mdown
en/unity/handling-errors.mdown

Fix dangling code tag, and fix error codes anchor.

Error Codes: Fix formatting and anchor

---

cn/rest/users.mdown

Tip off the REST API docs for the Simplified Chinese version. I have finished the users part and ask for review. The purpose of this pull request is also for testing whether Parse allows Simplified Chinese version of REST API section. If so, will keep contributing constantly.

Added cn/rest/users.mdown

---

ru/android/users.mdown

Update of russian version of documentation based on english version.

Actualization documentation

---

en/ios/handling-errors.mdown
en/ios/in-app-purchases.mdown
en/ios/local-datastore.mdown
en/ios/push-notifications.mdown
en/ios/queries.mdown
en/ios/user-interface.mdown

Link to #21 from areas in our Docs that are missing Swift samples.

Add link to open Swift samples issue.

---

en/ios/handling-errors.mdown
en/ios/in-app-purchases.mdown
en/ios/local-datastore.mdown
en/ios/push-notifications.mdown
en/ios/queries.mdown
en/ios/user-interface.mdown

Link issues: #41 #58 
@nlutsenko

Fixed issues #21: Provide missing Swift doc

---

en/rest/apps.mdown
en/rest/quick-reference.mdown

API will launch in the next couple days

Add /1/apps API to REST docs

---

en/ios/getting-started.mdown

Update the quickstart to be more precise.
@nlutsenko might want to take a look

Update iOS quickstart URL

---

en/common/cloud-code-modules.mdown
en/common/cloud-code.mdown
en/common/hosting.mdown
en/common/performance.mdown
en/common/security.mdown
en/js/files.mdown
en/js/push-notifications.mdown
en/js/roles.mdown

Went through the JS docs, fixed all of the broken links I could find

Update a number of links

---

en/android/queries.mdown
en/common/performance.mdown
en/dotnet/queries.mdown
en/ios/queries.mdown
en/js/queries.mdown
en/php/queries.mdown
en/rest/queries.mdown
en/unity/queries.mdown

Document startsWith/$regex, and include warning against using this over a large dataset. Regular expressions are discouraged, but are nonetheless part of the API.

Document regular expressions

---

en/unity/push-notifications.mdown

s/ParseUnityHelper/ParsePushUnityHelper
@nlutsenko

Fix Unity Helper

---

en/ios/users.mdown

Missing NSError in objective c example

---

en/common/relations.mdown

Included new common-js many-to-many example and moved other js example placed in incorrect block

Refactor and addition to many-to-many js examples

---

en/ios/users.mdown

Minor details about using the Facebook SDK

Facebook users

---

en/common/errors.mdown

Expand error message details for the 155 error code.

155 RequestLimitExceeded error message.

---

en/common/errors.mdown
en/common/performance.mdown
en/js/push-notifications.mdown

Organize error codes into related groups, and add resolution steps for operational issues.
Add httpRequest connection timeout to Limits section.

Organize error codes into sections

---

en/common/relations.mdown

This completes all PHP code in the relations section

Add PHP sample code to Relations section

---

en/js/users.mdown

Fixed a small Markdown styling inconsistency on JS - Users (en) documentation.

Fix styling.

---

en/android/push-notifications.mdown
en/ios/push-notifications.mdown

Instructions on the iOS and Android push troubleshooting sections about how to use the new Delivery Report to understand push problems.

Troubleshooting with the Push Delivery Report

---

en/ios/objects.mdown
en/ios/queries.mdown

Surfaced multiple times.
Last one was https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/280
Finally fully fixing it. This provides waaay more guarantees at compile time as well as eliminates need to do code branching.

Update PFQuery code samples for Swift 2.

---

en/ios/users.mdown

No significant change

---

en/common/sessions.mdown

Fix few typos in Sessions code samples.

---

en/unity/queries.mdown

queries.mdown: Fix typo.

---

en/ios/queries.mdown

Can't downcast a variable type to the same variable type
NSError is non-optional

Swift code fix

---

en/ios/objects.mdown

The last three parts are part of subclass, use title of three level is
more appropriate.

fix en/ios/objects.mdown subtitle

---

en/ios/user-interface.mdown

The image is not animated anyway.
@nlutsenko @hramos

Update todo_view to use .png instead of .gif

---

cn/js/users.mdown
en/js/users.mdown
jp/js/users.mdown
kr/js/users.mdown
ru/js/users.mdown
tw/js/users.mdown

`logOut` should be treated as async, since we introduced Sessions in April 2014.

Update docs to reflect the preferred async nature of logOut

---

en/ios/users.mdown

someone forgot to update this spot ;-)

fix deprecated usage: error.userInfo? --> error.userInfo
