ParsePlatform/Docs

- en/php/roles.mdown
Bug reported here: https://developers.facebook.com/bugs/1443247899303928/
To set role access by name we need to use `setRoleWriteAccessWithName`.
> Fix setRoleWriteAccess  typo in "Security for Other Objects" documentation

- en/ios/objects.mdown
parseClassName returns String, not String!
> Docs - incorrect function definition

- README.md
A handful of small grammar and style changes for the repo's README.
Changes "markdown versions" to "markdown sources"--I think that's a bit more specific/accurate.
Changes "have any fix or suggestion" to "have any fixes or suggestions" because I think that it reads better in plural.
Fixes grammatical issue in "shared amongst all platform[s]."
> Small grammar and style fixes for the README

- en/rest/users.mdown
As evidenced by the same sentence later in the parse website (where I read this document) the line should read "just by" and not "just be".
> this was a typo

- en/android/users.mdown
Migrated the Twitter REST API to v1.1 as the Twitter REST API v1 is no longer active.
> Migrated the Twitter REST API to v1.1

- en/common/performance.mdown
Updates the js samples to be referenced as common-js.
And also includes sample code for Objective-C and Swift.
Will be able to add the other language samples soon.
> Fix sample code for common performance section

- CONTRIBUTING.md
- README.md
This will replace the guidelines from https://github.com/ParsePlatform/Docs/wiki/Contributing-to-Docs.
Based on the great guidelines set forth by [atom](https://github.com/atom/atom/blob/master/CONTRIBUTING.md).
> Update Contributing guidelines.

- en/js/users.mdown
Docs say that users must be logged in before creating single-user-acl.
API (https://parse.com/docs/js/api/symbols/Parse.ACL.html#constructor)
doesn't indicate that
> Clarify single user acl doesn't need logging in

- en/js/queries.mdown
1. removes an unnecessary "of" (Typo) and clarifies language
2. removes a possible misconception that a queries match all items in a list
> (minor) Removes typo and Clarifies text

- en/common/security.mdown
GitHub doesn't allow commandeering like Phab does, so this pull request replaces https://github.com/ParsePlatform/Docs/pull/89 from Jamie. I removed the reference to CLP-ACL interaction docs in favor of a short description of the interaction. I'll add it back once we recover that section from the old docs.
> Add Pointer Permission docs.

- en/ios/users.mdown
The Twitter API v1 is no longer active, returns error.
> Update Twitter API url

- en/common/errors.mdown
Parse has added several error codes related to the new webhooks and schema APIs.
Some errors are grouped under the same error code but point to different specific problems. This is typically exposed as part of the error message, and we are adding them to the list for completeness.
It is also worth pointing out that the Parse API can return http error codes as well.
> Expand error list with new error codes. 

- en/common/errors.mdown
These are technically 141 errors, so it makes sense to list them in the errors list.
> Document success/error errors.

- en/rest/apps.mdown
- en/rest/getting-started.mdown
Apps guide was missing the application id token. Updated results example to use a generic app as an example.
> Fix app id tokens.

- en/ios/users.mdown
This is not needed anymore, as we fully support modulemaps which gets us Swift imports without bridging headers.
> Update ParseFacebookUtils swift example to use better import syntax.

- en/ios/getting-started.mdown
- en/ios/handling-errors.mdown
- en/ios/local-datastore.mdown
Use iOS 7.0 which is the current SDK version minimum deployment target, also updated all links to OSX to use proper name.
> Update minimum deployment target for iOS SDK.

- en/android/push-notifications.mdown
- en/ios/push-notifications.mdown
Move fields that are not used in a specific platform to the end of the list. They are still documented as they are of interest to anyone working on more than one platform.
Add a clarification on how often these fields are updated, per #174.
> Update special fields documentation in Push Notifications guides

- en/ios/user-interface.mdown
Some code samples are missing a Swift equivalent. If there is no placeholder text, the entire code sample disappears when Swift is selected as the language.
This PR should take care of the disappearing code samples when switching to Swift. We still need actual code in these boxes.
> Add missing Swift placeholder section.

- en/ios/objects.mdown
Fixed document to say PFObject instead of AnyObject
> Update sample code in Relational Queries for Swift 2

- en/ios/queries.mdown
It needs to be this way for legacy purposes mostly, but this would cause compile issues for people using our SDK in swift on 64-bit targets.
> Count for queries should be Int32 in swift.

- en/common/command-line.mdown
The documentation states `parse configure accountkey` but the example uses `parse configure key` - this changes the latter to the former, because that is also what's used in the Parse CLI messages.
> Synchronize accountkey command example

- en/js/objects.mdown
Added clarification that objectId, updatedAt, and createdAt cannot be modified with .set nor retrieved with .get. 
This has been a source of confusion for some: https://parse.com/questions/javascript-get-objectid
> Special properties are not exposed to set and get methods

- en/common/sessions.mdown
The 'pseudo' implementation of the ParseErrorHandler class ends with '});' which is nice if it were an inner class somewhere but it isn't in this example, so it should really end with just '}'.
> Syntax fix in sessions.md

- en/ios/push-notifications.mdown
For Push Notification, in Obj-C guide, responding to the payout code example is:
```objc
NSString *photoId = [notificationPayload objectForKey:@"p"];
PFObject *targetPhoto = [PFObject objectWithoutDataWithClassName:@"Photo"   objectId:photoId];
```
But in swift it is:
```swift
let photoId = notificationPayload["p"] as? NSString
let targetPhoto = PFObject(withoutDataWithClassName: "Photo", objectId: "xWMyZ4YEGZ")
```
Which should be using ```photoId``` as well.
> Fix photoId

- en/cloudcode/cloud-code-modules.mdown
In your Parse documentation.
https://parse.com/docs/cloudcode/guide#cloud-code-modules-sendgrid
Search for "SendGrid.sendEmail("
(I think) that should be a lowercase "S", rewritten as "sendGrid.sendEmail("
Thats it...
Sagan
> Codefix - ReferenceError: SendGrid is not defined

- en/common/security.mdown
One of the pointer permissions examples had which field gained access to what action inverted in the english description but correct in the code and data model example.
> Correct inverted example in pointer permission example.

- en/cloudcode/cloud-code-advanced.mdown
I had an issue running a job with a string with special characters and noticed that the problem was that the charset wasn't specified. Maybe is better to add the charset to the example for future new users.
> Added the charset for the background job request

- en/js/objects.mdown
For array fields of an Object, you need to call `save()` every time you use `unset()`. This is explained for the `remove()` function but not for the `unset()` one.
> Update comments for the unset() function

- en/rest/push-notifications.mdown
Actually one should set `push_time` parameter not `timeZone`.
> Push notifications docs have misleading parameter name

- en/php/queries.mdown
Added the missing square brackets to the select example.
https://twitter.com/geoffroymorel/status/690277503336857600
> Typo in select example

- en/ios/extensions.mdown
This doesn't work on watchOS 2 and might be confusing.
> Remove references to WatchKit from Extensions guide.

- en/ios/objects.mdown
SaveInBackgroundWithTarget is no longer in the PFObject Class Reference, SaveInBackgroundWithBlock is used instead.
> SaveInBackgroundWithTarget is deprecated
